/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LockRouteImport } from './routes/lock'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AuthUnlockedRouteImport } from './routes/_auth/_unlocked'
import { Route as AuthRecoverRouteImport } from './routes/_auth/recover'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthUnlockRouteImport } from './routes/_auth/unlock'
import { Route as AuthSetupRecoveryCodeRouteImport } from './routes/_auth/setup_.recovery-code'
import { Route as AuthUnlockedVaultIndexRouteImport } from './routes/_auth/_unlocked/vault.index'
import { Route as AuthUnlockedVaultFolderIdRouteImport } from './routes/_auth/_unlocked/vault.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnlockedRoute = AuthUnlockedRouteImport.update({
  id: '/_unlocked',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnlockRoute = AuthUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRecoveryCodeRoute = AuthSetupRecoveryCodeRouteImport.update({
  id: '/setup_/recovery-code',
  path: '/setup/recovery-code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnlockedVaultIndexRoute = AuthUnlockedVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AuthUnlockedRoute,
} as any)
const AuthUnlockedVaultFolderIdRoute =
  AuthUnlockedVaultFolderIdRouteImport.update({
    id: '/vault/$folderId',
    path: '/vault/$folderId',
    getParentRoute: () => AuthUnlockedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lock': typeof LockRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/recover': typeof AuthRecoverRoute
  '/setup': typeof AuthSetupRoute
  '/unlock': typeof AuthUnlockRoute
  '/setup/recovery-code': typeof AuthSetupRecoveryCodeRoute
  '/vault/$folderId': typeof AuthUnlockedVaultFolderIdRoute
  '/vault/': typeof AuthUnlockedVaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lock': typeof LockRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/recover': typeof AuthRecoverRoute
  '/setup': typeof AuthSetupRoute
  '/unlock': typeof AuthUnlockRoute
  '/setup/recovery-code': typeof AuthSetupRecoveryCodeRoute
  '/vault/$folderId': typeof AuthUnlockedVaultFolderIdRoute
  '/vault': typeof AuthUnlockedVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/lock': typeof LockRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/_auth/_unlocked': typeof AuthUnlockedRouteWithChildren
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_auth/unlock': typeof AuthUnlockRoute
  '/_auth/setup_/recovery-code': typeof AuthSetupRecoveryCodeRoute
  '/_auth/_unlocked/vault/$folderId': typeof AuthUnlockedVaultFolderIdRoute
  '/_auth/_unlocked/vault/': typeof AuthUnlockedVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lock'
    | '/sign-in'
    | '/sign-out'
    | '/recover'
    | '/setup'
    | '/unlock'
    | '/setup/recovery-code'
    | '/vault/$folderId'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lock'
    | '/sign-in'
    | '/sign-out'
    | '/recover'
    | '/setup'
    | '/unlock'
    | '/setup/recovery-code'
    | '/vault/$folderId'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/lock'
    | '/sign-in'
    | '/sign-out'
    | '/_auth/_unlocked'
    | '/_auth/recover'
    | '/_auth/setup'
    | '/_auth/unlock'
    | '/_auth/setup_/recovery-code'
    | '/_auth/_unlocked/vault/$folderId'
    | '/_auth/_unlocked/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LockRoute: typeof LockRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_unlocked': {
      id: '/_auth/_unlocked'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthUnlockedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unlock': {
      id: '/_auth/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthUnlockRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup_/recovery-code': {
      id: '/_auth/setup_/recovery-code'
      path: '/setup/recovery-code'
      fullPath: '/setup/recovery-code'
      preLoaderRoute: typeof AuthSetupRecoveryCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_unlocked/vault/': {
      id: '/_auth/_unlocked/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AuthUnlockedVaultIndexRouteImport
      parentRoute: typeof AuthUnlockedRoute
    }
    '/_auth/_unlocked/vault/$folderId': {
      id: '/_auth/_unlocked/vault/$folderId'
      path: '/vault/$folderId'
      fullPath: '/vault/$folderId'
      preLoaderRoute: typeof AuthUnlockedVaultFolderIdRouteImport
      parentRoute: typeof AuthUnlockedRoute
    }
  }
}

interface AuthUnlockedRouteChildren {
  AuthUnlockedVaultFolderIdRoute: typeof AuthUnlockedVaultFolderIdRoute
  AuthUnlockedVaultIndexRoute: typeof AuthUnlockedVaultIndexRoute
}

const AuthUnlockedRouteChildren: AuthUnlockedRouteChildren = {
  AuthUnlockedVaultFolderIdRoute: AuthUnlockedVaultFolderIdRoute,
  AuthUnlockedVaultIndexRoute: AuthUnlockedVaultIndexRoute,
}

const AuthUnlockedRouteWithChildren = AuthUnlockedRoute._addFileChildren(
  AuthUnlockedRouteChildren,
)

interface AuthRouteChildren {
  AuthUnlockedRoute: typeof AuthUnlockedRouteWithChildren
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthUnlockRoute: typeof AuthUnlockRoute
  AuthSetupRecoveryCodeRoute: typeof AuthSetupRecoveryCodeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUnlockedRoute: AuthUnlockedRouteWithChildren,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthUnlockRoute: AuthUnlockRoute,
  AuthSetupRecoveryCodeRoute: AuthSetupRecoveryCodeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LockRoute: LockRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
